### PR TITLE
First iteration

### PR DESCRIPTION
**Pull request by NourAbdellatif**
- Working demo of revamped template with all the content of the previous gedygroup
- As discussed not all the images/text is fixed
- Awaiting comments and changes

### CODE REVIEW

**Comment by hesham-gedygroup** [comment]
I'm happy to merge this, however this is impossible to review,  I'd like that we live-QA as review instead

Please for the following pull requests, make sure you have as many commits as possible.
A commit should cover between 1-2 hours worth of work and follows the Single responsibility principle from the SOLID principle.
Please have a look at good naming convention convention here for the up-coming PRs. 
https://cbea.ms/git-commit/

**Comment by NourAbdellatif** [comment]
Updated the landing page to meet the specifications discussed during our meeting

**Comment by hesham-gedygroup** [comment]
image
The text is now floating into each others in the footer, please separate those lines.

**Comment by hesham-gedygroup** [comment]
Please wrap your implementation so we are still able to build and deploy easily with firebase 
https://www.opencodez.com/java-script/static-website-with-node-js-webserver.htm

**Comment by hesham-gedygroup** [comment]
Website title is Sland - HTML title home, it should be Gedygroup

**Comment by hesham-gedygroup** [comment]
Please check why the missing images in the first carousel when deployed.

**Comment by hesham-gedygroup** [comment]
And fix the footer as we discussed :D

**Pull request merged**
